excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://riloaw.github.io
title: Rizal Loa Wanda
email: riloaw@gmail.com
author: Rizal Loa Wanda
description: Ini Tentang Saya Rizal Loa
paginate: 5
google_analytics: G-151FCF39DE
